import '../styles/globals.css'
import Head from "next/head";
import styles from "../styles/Home.module.css";
import {Box, Container, CssBaseline} from "@mui/material";

function MyApp({Component, pageProps}) {
    return <>
        <Head>
            <title>Maccas Road Rally 2022</title>
            <link
                rel="stylesheet"
                href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
            />
            <link
                rel="stylesheet"
                href="https://fonts.googleapis.com/icon?family=Material+Icons"
            />
            <meta name="viewport" content="initial-scale=1, width=device-width"/>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
        <div className={styles.container}>
            <Container component="main" maxWidth="xs">
                <CssBaseline/>

                <Box
                    sx={{
                        display: 'flex',
                        flexDirection: 'column',
                        alignItems: 'center',
                        justifyContent: 'center',
                        paddingTop: '100px',
                        paddingBottom: '100px',
                        minHeight: '100vh',
                    }}
                >
                    <Component {...pageProps} />
                </Box>
            </Container>
        </div>
    </>
}

export default MyApp
